language: rust

jobs:
  include:
    - name: Ubuntu Xenial
      os: linux
      dist: xenial

before_install:
  - rustup component add rustfmt clippy

script:
  - cargo fmt -- --check && cargo test --release && cargo clippy

cache: cargo
